version: '3'
services:

  #PHP Service
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app2
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app2
      SERVICE_TAGS: dev2
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app2-network

  #Nginx Service
  webserver2:
    image: nginx:alpine
    container_name: webserver2
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app2-network

#Docker Networks
networks:
  app2-network:
    driver: bridge
